mavros/setpoint_raw:
  ros__parameters:
    thrust_scaling: 1.0       # used in setpoint_raw attitude callback.
    # Note: PX4 expects normalized thrust values between 0 and 1, which means that
    # the scaling needs to be unitary and the inputs should be 0..1 as well.