mavros/imu:
  ros__parameters:
    # imu_pub
    frame_id: "base_link"
    # need find actual values
    linear_acceleration_stdev: 0.0003
    angular_velocity_stdev: 0.0003490659 
    orientation_stdev: 1.0
    magnetic_stdev: 0.0