mavros/time:
  ros__parameters:
    # Common configuration for PX4 autopilot
    #
    # node:
    time_ref_source: "gcu"  # time_reference source
    timesync_mode: MAVLINK
    timesync_avg_alpha: 0.6 # timesync averaging factor
    